/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ../../../public/cube1.glb
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/cube1.glb");
  return (
    <group {...props} dispose={null}>
      <pointLight
        intensity={54351.413}
        decay={2}
        position={[4.076, 5.904, -1.005]}
        rotation={[-1.839, 0.602, 1.932]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={0.1}
        fov={22.895}
        position={[7.359, 4.958, 6.926]}
        rotation={[-0.627, 0.71, 0.441]}
      />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload("/cube1.glb");
